# Metadata musictag keys
ALBUMARTIST = 'albumartist'
ARTWORK = 'artwork'
DISCNUMBER = 'discnumber'
GENRE = 'genre'
LYRICS = 'lyrics'
TOTALDISCS = 'totaldiscs'
TOTALTRACKS = 'totaltracks'
TRACKNUMBER = 'tracknumber'
TRACKTITLE = 'tracktitle'
YEAR = 'year'

# Both
ALBUM = 'album'
ARTIST = 'artist'
COMPILATION = "compilation"

# API Dictionary Keys
ALBUMS = 'albums'
ALBUM_TYPE = 'album_type'
ARTISTS = 'artists'
DISC_NUMBER = 'disc_number'
DISPLAY_NAME = 'display_name'
DURATION_MS = 'duration_ms'
ERROR = 'error'
EXPLICIT = 'explicit'
GENRES = 'genres'
HREF = 'href'
ID = 'id'
IMAGES = 'images'
IS_PLAYABLE = 'is_playable'
ITEMS = 'items'
NAME = 'name'
OWNER = 'owner'
PLAYLIST = 'playlist'
PLAYLISTS = 'playlists'
RELEASE_DATE = 'release_date'
SHOW = 'show'
TOTAL_TRACKS = "total_tracks"
TRACK = 'track'
TRACKS = 'tracks'
TRACK_NUMBER = 'track_number'
URL = 'url'
WIDTH = 'width'

# Both
TYPE = 'type'

# API Account Attributes
AUTHORIZATION = 'Authorization'
LIMIT = 'limit'
OFFSET = 'offset'
PLAYLIST_READ_PRIVATE = 'playlist-read-private'
PREMIUM = 'premium'
USER_FOLLOW_READ = 'user-follow-read'
USER_LIBRARY_READ = 'user-library-read'
USER_READ_EMAIL = 'user-read-email'

# API URLs
BASE_URL = 'https://api.sp'+'otify.com/v1/'
ALBUM_URL = BASE_URL + 'albums'
ARTIST_URL = BASE_URL + 'artists'
EPISODE_INFO_URL = BASE_URL + 'episodes'
PLAYLISTS_URL = BASE_URL + 'playlists'
SEARCH_URL = BASE_URL + 'search'
SHOWS_URL = BASE_URL + 'shows'
TRACKS_URL = BASE_URL + 'tracks'
TRACK_STATS_URL = BASE_URL + 'audio-features/'
USER_FOLLOWED_ARTISTS_URL = BASE_URL + 'me/following?type=artist'
USER_PLAYLISTS_URL = BASE_URL + 'me/playlists'
USER_SAVED_TRACKS_URL = BASE_URL + 'me/tracks'
PARTNER_URL = 'https://api-partner.sp'+'otify.com/pathfinder/v1/query?operationName=getEpisode&variables={"uri":"sp'+'otify:episode:'
PERSISTED_QUERY = '{"persistedQuery":{"version":1,"sha256Hash":"224ba0fd89fcfdfb3a15fa2d82a6112d3f4e2ac88fba5c6713de04d1b72cf482"}}'

# System Constants
LINUX_SYSTEM = 'Linux'
WINDOWS_SYSTEM = 'Windows'

# FFMPEG
CODEC_MAP = {
    'aac': 'aac',
    'fdk_aac': 'libfdk_aac',
    'mp3': 'libmp3lame',
    'ogg': 'copy',
    'opus': 'libopus',
    'vorbis': 'copy',
    'copy': 'copy'
}
EXT_MAP = {
    'aac': 'm4a',
    'fdk_aac': 'm4a',
    'mp3': 'mp3',
    'ogg': 'ogg',
    'opus': 'ogg',
    'vorbis': 'ogg',
    'copy': 'ogg'
}

# Config Keys
DEBUG = "DEBUG"
ROOT_PATH = 'ROOT_PATH'
ROOT_PODCAST_PATH = 'ROOT_PODCAST_PATH'
SKIP_EXISTING = 'SKIP_EXISTING'
SKIP_PREVIOUSLY_DOWNLOADED = 'SKIP_PREVIOUSLY_DOWNLOADED'
DOWNLOAD_FORMAT = 'DOWNLOAD_FORMAT'
BULK_WAIT_TIME = 'BULK_WAIT_TIME'
OVERRIDE_AUTO_WAIT = 'OVERRIDE_AUTO_WAIT'
CHUNK_SIZE = 'CHUNK_SIZE'
SPLIT_ALBUM_DISCS = 'SPLIT_ALBUM_DISCS'
DOWNLOAD_REAL_TIME = 'DOWNLOAD_REAL_TIME'
LANGUAGE = 'LANGUAGE'
DOWNLOAD_QUALITY = 'DOWNLOAD_QUALITY'
TRANSCODE_BITRATE = 'TRANSCODE_BITRATE'
SONG_ARCHIVE_LOCATION = 'SONG_ARCHIVE_LOCATION'
SAVE_CREDENTIALS = 'SAVE_CREDENTIALS'
CREDENTIALS_LOCATION = 'CREDENTIALS_LOCATION'
OUTPUT = 'OUTPUT'
PRINT_SPLASH = 'PRINT_SPLASH'
PRINT_SKIPS = 'PRINT_SKIPS'
PRINT_DOWNLOAD_PROGRESS = 'PRINT_DOWNLOAD_PROGRESS'
PRINT_ERRORS = 'PRINT_ERRORS'
PRINT_DOWNLOADS = 'PRINT_DOWNLOADS'
PRINT_API_ERRORS = 'PRINT_API_ERRORS'
TEMP_DOWNLOAD_DIR = 'TEMP_DOWNLOAD_DIR'
MD_DISC_TRACK_TOTALS = "MD_DISC_TRACK_TOTALS"
MD_SAVE_GENRES = 'MD_SAVE_GENRES'
MD_ALLGENRES = 'MD_ALLGENRES'
MD_GENREDELIMITER = 'MD_GENREDELIMITER'
MD_ARTISTDELIMITER = 'MD_ARTISTDELIMITER'
MD_SAVE_LYRICS = 'MD_SAVE_LYRICS'
PRINT_PROGRESS_INFO = 'PRINT_PROGRESS_INFO'
PRINT_WARNINGS = 'PRINT_WARNINGS'
RETRY_ATTEMPTS = 'RETRY_ATTEMPTS'
CONFIG_VERSION = 'CONFIG_VERSION'
DOWNLOAD_LYRICS = 'DOWNLOAD_LYRICS'
OUTPUT_PLAYLIST = 'OUTPUT_PLAYLIST'
OUTPUT_PLAYLIST_EXT = 'OUTPUT_PLAYLIST_EXT'
OUTPUT_LIKED_SONGS = 'OUTPUT_LIKED_SONGS'
OUTPUT_SINGLE = 'OUTPUT_SINGLE'
OUTPUT_ALBUM = 'OUTPUT_ALBUM'
DISABLE_DIRECTORY_ARCHIVES = 'DISABLE_DIRECTORY_ARCHIVES'
LYRICS_LOCATION = 'LYRICS_LOCATION'
FFMPEG_LOG_LEVEL = 'FFMPEG_LOG_LEVEL'
PRINT_URL_PROGRESS = 'PRINT_URL_PROGRESS'
PRINT_ALBUM_PROGRESS = 'PRINT_ALBUM_PROGRESS'
PRINT_ARTIST_PROGRESS = 'PRINT_ARTIST_PROGRESS'
PRINT_PLAYLIST_PROGRESS = 'PRINT_PLAYLIST_PROGRESS'
EXPORT_M3U8 = 'EXPORT_M3U8'
LIKED_SONGS_ARCHIVE_M3U8 = 'LIKED_SONGS_ARCHIVE_M3U8'
ALBUM_ART_JPG_FILE = 'ALBUM_ART_JPG_FILE'
MAX_FILENAME_LENGTH = 'MAX_FILENAME_LENGTH'
ALWAYS_CHECK_LYRICS = 'ALWAYS_CHECK_LYRICS'
M3U8_LOCATION = 'M3U8_LOCATION'
M3U8_REL_PATHS = 'M3U8_REL_PATHS'
DOWNLOAD_PARENT_ALBUM = 'DOWNLOAD_PARENT_ALBUM'
REDIRECT_URI = "REDIRECT_URI"
DISABLE_SONG_ARCHIVE = 'DISABLE_SONG_ARCHIVE'
